services:
  chall:
    build: .
    cap_add:
      - SYS_ADMIN
    volumes:
      - /sys/kernel/tracing/:/sys/kernel/tracing/:ro
    ports:
      - 1337:22
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 250M
          pids: 256
